---
title: '**Cross Country Workout Data**'
jupyter: python3
---

*Created by Ryan Sponzilli*


```{python}
#| echo: false
import pandas as pd
import geopandas as gpd
import contextily as cx
import shapely
import numpy as np
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
import matplotlib.pyplot as plt
import seaborn as sns
import glob

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import HDBSCAN

import seasons
import plotting
from transformers import TrackCellTransformer
```

## Table of Contents
* [1. Introduction](#introduction)
    * [1.1 Goals]()
* [2. Data Cleaning](#data-cleaning)
    * [2.1 GPX File List]()
        * [2.1.1 Parse Filename]()
        * [2.1.2 Filter Time Period]()
        * [2.1.3 Year & Season Bucketing]()
    * [2.2 Workouts XML]()
        * [2.2.1 Filter Time Period]()
        * [2.2.2 Filter Activity Type]()
    * [2.3 Merge GPX File List with Workout Data]()
    * [2.4 GPX Track Data Extraction]()
        * [2.4.3 Statistics]()
        * [2.4.2 Pause Detection]()
* [3. Route Clustering](#route-clustering)
    * [4.1 Unsupervised Route Clustering]()
    * [4.2 Creating a Route Library]()
    * [4.2 Supervised Route Clustering]()
* [4. Next Steps](#next-steps)



## 1. Introduction 
<a id="introduction"></a>

I ran cross country and track all four years that I was in high school, and I recorded every single run on my Apple Watch. I believe that this is a very unique trove of data that has the potential to be very interesting and very personal.

I obtained the raw data by exporting my Apple Health data. This export gave me a 2.23 GB `.xml` file and a folder containing 1,232 `.gpx` files.

I have constructed this document to explain each decision I made while working with this data and present the results. My work on this project was very nonlinear and experimental, as is anything that is being figured out for the first time, so please be aware that I have taken my final process and presented it in a logical and linear order here. Note that not all of the code is visible, and that the code that is made visible is meant to illustrate the processes.

### 1.1 Goals

* Learn how to work with geospatial data and tools:
    * Learn how to manipulate geospatial data with the `geopandas` library.
    * Learn how to create effective visualizations of geospatial data.
* Develop a data pipeline to ingest the raw data and output a processed dataset ready for analysis and visualization:
    * Use machine learning techniques to perform route geoclustering and route decomposition.
    * Categorize runs into specific types (e.g., workouts, long runs, normal runs).
    * Thoroughly document every decision and assumption made while processing the data.
* Analyze the data to create visually appealing and informative maps and charts:
    * Understand the geographic distribution of my runs.
    * Understand my training regimen and how it evolved over time.
    * Understand how I improved over my four years.



<!-- The `.xml` file contains a `Record` tag, which contains a data record for a health statistic, such as *ActiveEnergyBurned*, *HeartRate*, or *EnvironmentalAudioExposure*. This will be useful for getting fitness statistics, such as heart rate, VO2 max, and calories burned. -->

```{python}
#| echo: false
# df = pd.read_parquet("data/intermediate/record_data.parquet")
# print("Sample of 3 \"Record\" records:")
# display(df.sample(3))
# print(f"Dataframe Length: {len(df)} Rows")
```

## 2. Data Cleaning
<a id="data_cleaning"></a>

The raw data must be converted into a convenient form, have certain constraints applied, and new features derived. As shown above, the raw data is spread across several different sources which must be integrated together.

### 2.1 GPX File List

The first piece of this puzzle is to assemble a list of all the GPX files. I will start by obtaining all of the filepaths.

```{python}
#| echo: false
path = "/Users/ryansponzilli/Developer/Python Projects/health-data/data/raw/apple_health/apple_health_export/workout-routes"
df_tracks = pd.DataFrame({"track_file": glob.glob(path + "/*")})
print("Here are the filepaths:")
display(df_tracks.sample(3))
print(f"Dataframe Length: {len(df_tracks)} Rows")
print(f"Example file name: {df_tracks.iloc[0].values[0].split("/")[-1]}")
```

Each file name contains a date and time (referred to as a datetime). This datetime corresponds to the creation of the file. This is an important piece of information, so I will extract it from the file name and put it in its own column. It will also be useful to have a column with the date only.

```{python}
# parse track file dates
df_tracks["track_file_datetime"] = df_tracks["track_file"].apply(
    lambda x: datetime.strptime(
        x.split("/")[-1].removeprefix("route_")
        .removesuffix(".gpx"), "%Y-%m-%d_%I.%M%p")
        .replace(tzinfo=ZoneInfo("America/Chicago")
    )
)
df_tracks["track_file_date"] = df_tracks["track_file_datetime"].dt.date
```
```{python}
#| echo: false
print("Updated table with dates extracted:")
display(df_tracks.sample(3))
print(f"Dataframe Length: {len(df_tracks)} Rows")
```

The next thing I want to do is to filter for only the runs that occurred while I was in high school. Additionally, I want to bucket the runs into each year of high school and each season of the year. To do this, I went back into my calendar and manually created a table with the necessary information.

```{python}
#| echo: false
print(f"Minimum Date: {seasons.MIN_DATE}")
print(f"Maximum Date {seasons.MAX_DATE}")
print("Year and Seasons Buckets:")
display(seasons.seasons)
```

<br>

Now I will apply the minimum and maximum date constraints, and apply the bucketing.

```{python}
# bucket dates into seasons
df_tracks = (
    df_tracks.loc[(df_tracks["track_file_datetime"] >= seasons.MIN_DATE) & (df_tracks["track_file_datetime"] <= seasons.MAX_DATE)]
    .sort_values("track_file_datetime")
    .reset_index(drop=True)
)
df_tracks["year"] = df_tracks["track_file_datetime"].apply(lambda x: seasons.bucket_date(x)[0])
df_tracks["season"] = df_tracks["track_file_datetime"].apply(lambda x: seasons.bucket_date(x)[1])
```
```{python}
#| echo: false
print("Updated table with dates bucketed:")
display(df_tracks.sample(3))
print(f"Dataframe Length: {len(df_tracks)} Rows")
```

<br>

### 2.2 Workouts XML

The `.xml` file contains a `Workout` tag, which contains a data record for individual workouts. Not much useful information is provided in these records, just dates, a duration, and the type of activity. The type of activity is the most important field. Since the GPX tracks do not specify what activity they contain, I will need to link them to these records to identifiy which ones correspond to runs, and not to walks, bike rides, or hikes.

```{python}
#| echo: false
df_workouts = pd.read_parquet("data/intermediate/workout_data.parquet")
print("Sample of 3 \"Workout\" records:")
display(df_workouts.sample(3))
print(f"Dataframe Length: {len(df_workouts)} Rows")
```

To separate runs from hikes, walks, and bike rides, I need to cross reference each GPX file with its corresponding entry in the "Workouts" table from the `.xml` file. I will go ahead and filter the time period to the minimum and maximum dates. I also want to select only workouts that came from my Apple Watch. I need to exclude any Strava runs since I do not have any GPX files associated with them.

```{python}
# parse data types
df_workouts['creationDate'] = pd.to_datetime(df_workouts['creationDate'])
df_workouts['startDate'] = pd.to_datetime(df_workouts['startDate'])
df_workouts['endDate'] = pd.to_datetime(df_workouts['endDate'])
df_workouts['duration'] = df_workouts['duration'].astype(float)

# filter time period
df_workouts = df_workouts.loc[(df_workouts['startDate'] >= pd.to_datetime(seasons.MIN_DATE, utc=True)) & (df_workouts['startDate'] <= pd.to_datetime(seasons.MAX_DATE, utc=True))]

# get relevant data
df_workouts = df_workouts.loc[df_workouts['sourceName'] != "Strava"]
df_workouts = df_workouts[["workoutActivityType", "creationDate", "startDate", "endDate", "duration", "durationUnit"]].rename(columns={"creationDate": "creation_datetime", "startDate": "start_datetime", "endDate": "end_datetime"})
df_workouts = df_workouts.sort_values("start_datetime").reset_index(drop=True)
```
```{python}
#| echo: false
print("Workouts table after parsing:")
display(df_workouts.sample(3, random_state=5).sort_values("start_datetime"))
print(f"Dataframe Length: {len(df_workouts)} Rows")
```

### 2.3 Merge GPX File List with Workouts XML

Both tables are prepared, but there is one obstacle remaining to merging them together. The `track_file_datetime` column in the GPX file dataframe refers to a creation time, so in the merge, we will reference this column to the `creation_datetime` column in the Workouts dataframe. However, due to whatever reason, these datetimes will not line up identically, they may be offset by several seconds or minutes. To fix this, I will iterate through each `track_file_datetime` in the GPX track dataframe and locate the closest match in the Workouts dataframe, and store this value in a new temporary column. Then I will merge on this temporary column, and drop any rows that are not running workouts.

```{python}
#| echo: false
df_merged = pd.read_parquet("data/intermediate/track_info_merged.parquet")
print("Merged Dataframes:")
display(df_merged.head(3))
print(f"Dataframe Length: {len(df_merged)} Rows")
```

Notice that we dropped from 1268 rows to 1033 rows. We have successfully removed all of the non-running GPX tracks from the dataframe.

<br>

### 2.4 GPX Track Data Extraction
Now that we have a clean dataset containing all of the runs, it's time to look inside the GPX files themselves. For each GPX file, the data points are a time series sampled once per second where each timestamp has an associated latitude/longitude coordinate pair and an elevation. We can extract a lot of information from just this information.

A single `.gpx` file can contain multiple data layers:

```{python}
#| echo: false
gpx_file = glob.glob("data/raw/workout-routes/*.gpx")[0]
print("GPX File Layers:")
display(gpd.list_layers(gpx_file))
```

<br>

However, only two of the layers contain any data. These are the `tracks` layer and the `track_points` layer. I can load these individually using `geopandas.read_file()`. Most of the columns do not contain any data, but what really matters is the `geometry` column.

```{python}
#| echo: false
gdf = gpd.read_file(gpx_file, layer='tracks')
print("\"tracks\" Layer:")
display(gdf)
```

<br>

```{python}
#| echo: false
gdf = gpd.read_file(glob.glob("data/raw/workout-routes/*.gpx")[0], layer='track_points')
print("\"track_points\" Layer:")
display(gdf.head(3))
print(f"Dataframe Length: {len(gdf)} Rows")
```

The `track_points` layer is more useful, since it provides a more granular representation of the data. For each point, it gives a coordinate, timestamp, and elevation. These can be used to derive statistics such as elapsed distance, running pace, elevation change, and later, for route geoclustering.

```{python}
#| echo: false
fig, ax = plt.subplots(figsize=(5,5))
print("The track points plotted on a map:")
plotting.plot_map(gdf, ax)
plt.show()
```

Before we get into detecting pauses and deriving statistics, I will properly parse the `track_points` dataframe and extract two helper columns, `dt` and `dx`, describing the change in time and position, respectively, from one track point to the next.

```{python}
# parse file
gdf = gdf[["time", "ele", "geometry"]]
gdf["time"] = pd.to_datetime(gdf["time"])
gdf = gdf.rename(columns={"time": "datetime", "ele": "elevation"})

# create helper columns
gdf['dt'] = gdf["datetime"].diff()
gdf_utm = gdf.to_crs(gdf.estimate_utm_crs())
gdf["dx"] = gdf_utm["geometry"].distance(gdf_utm["geometry"].shift())
```

```{python}
#| echo: false
display(gdf.head(3))
```

#### 2.4.1 Pause Detection
Before I can extract summary statistics, it is necessary to account for gaps in the data which can distort the statistics. Many runs contain pauses, where I manually paused the run to wait to cross the street, take a break, or for a rest between workout segments. In some cases, the pause may be extra long because I forgot to resume the run.

Left as-is, these pauses will result in calculating incorrect statistics like duration, distance, and pace. These also cause the map plots to interpolate the track line over the gap which looks funny and does not accurately reflect the run.

```{python}
#| echo: false
fig, ax = plt.subplots(figsize=(6,6))
pause_line = df_merged.loc[df_merged['track_file_datetime'] > pd.to_datetime(datetime(2023, 2, 7), utc=True)][0:1]
print("Pauses lead to misleading maps like this one where I forgot to unpause the run:")
gdf_temp = gpd.read_file(pause_line['track_file'].iloc[0], layer="tracks")
plotting.plot_map(gdf_temp, ax)
plt.show()

#| echo: false
print("Detecting pauses and splitting the track into segments will yield a more accurate plot:")

gdf_temp_points = gpd.read_file(pause_line['track_file'].iloc[0], layer="track_points")
# parse file
gdf_temp_points = gdf_temp_points[["time", "ele", "geometry"]]
gdf_temp_points["time"] = pd.to_datetime(gdf_temp_points["time"])
gdf_temp_points = gdf_temp_points.rename(columns={"time": "datetime", "ele": "elevation"})
# create helper columns
gdf_temp_points['dt'] = gdf_temp_points["datetime"].diff()
# detect pauses
pause_idx = list(gdf_temp_points.loc[gdf_temp_points['dt'] > timedelta(seconds=1)].index)
gdf_temp_points['pause_segment'] = None
segment_idx = ([0] + pause_idx + [len(gdf_temp_points)])
for i in range(len(segment_idx) - 1):
    gdf_temp_points.loc[segment_idx[i]:segment_idx[i+1], 'pause_segment'] = i
# remove segments less than 10 seconds
gdf_temp_points = gdf_temp_points.groupby("pause_segment", group_keys=False).filter(lambda x: len(x) > 10)

fig, ax = plt.subplots(figsize=(6,6))
gdf_temp.loc[gdf_temp.index == 0, 'geometry'] = shapely.MultiLineString([shapely.LineString(group['geometry']) for _, group in gdf_temp_points.groupby('pause_segment')])
plotting.plot_map(gdf_temp, ax)
plt.show()
```

Each run is nominally sampled every second, so pauses can be detected by any gaps in the time series greater than 1 second. To be on the safe side, I will use a gap threshold of 5 seconds.

These are the required steps:

1. Locate indices of time-pauses in each run, with threshold of 5 seconds.
2. Split the data into segments along the located indices by creating an indicator column.
3. Remove segments less than 10 seconds, since these are mistakes with no meaningful value.

```{python}
#| echo: false
fig, ax = plt.subplots(figsize=(5,5))
print("The rest of this section will continue using this track as an example:")
plotting.plot_map(gdf, ax)
plt.show()
```

```{python}
# split into segments at pause indices
pause_idx = list(gdf.loc[gdf['dt'] > timedelta(seconds=1)].index)
gdf['pause_segment'] = None
segment_idx = ([0] + pause_idx + [len(gdf)])
for i in range(len(segment_idx) - 1):
    gdf.loc[segment_idx[i]:segment_idx[i+1], 'pause_segment'] = i

# remove segments less than 10 seconds
gdf = gdf.groupby("pause_segment", group_keys=False).filter(lambda x: len(x) > 10)
```

```{python}
#| echo: false
display(gdf.sample(5).sort_values("datetime"))
num_pauses = len(gdf.loc[gdf['dt'] > timedelta(seconds=1)])
print(f"Number of Pauses Detected: {num_pauses}")
```

#### 2.4.2 Rolling Pace
Before moving on to calculating summary statistics, I need to create a column for the current pace. The pace is my speed, usually measured in minutes per mile, so it is calculated by `dt` / `dx`. To calculate the pace, I will use a rolling average from the last 10 seconds, and importantly doing this separately within each pause segment. A side effect of using a rolling window of 10 seconds is that you cannot calculate it for the first 10 seconds, so we fill simply backfill the pace for the first 10 seconds.

```{python}
# calculate pace for each pause segment separately
def calculate_rolling_pace(gdf):
    # use a 10 second rolling window for calculating pace
    gdf["pace (min/mi)"] = (gdf["dt"].cumsum().dt.total_seconds() / 60).diff(10) / (gdf["dx"].cumsum() / 1609).diff(10)
    # backfill nans that resulted from the rolling window
    gdf["pace (min/mi)"] = gdf["pace (min/mi)"].bfill()
    return gdf
gdf = gdf.groupby('pause_segment').apply(calculate_rolling_pace).reset_index().drop(columns=["level_1"], errors='ignore')
```

```{python}
#| echo: false
display(gdf.sample(5).sort_values("datetime"))
```

#### 2.4.3 Summary Statistics
I would like to extract a few summary statistics from each run merge them into our master dataframe. These include:

* **start_point**: the first point in the run.
* **end_point**: the last point in the run.
* **start_datetime**: the first timestamp in the run.
* **end_datetime**: the last timestamp in the run.
* **num_pauses**: the number of pauses, where a pause is defined as a gap greater than five seconds.
* **total_duration**: the total time elapsed from starting the run to ending the run, including all pauses.
* **active_duration**: the total time elapsed from starting the run to ending the run, excluding all pauses.
* **total_distance**: the total distance run in miles, excluding distance covered during pauses.
* **average_pace**: the average pace during the run.
* **total_ascent**: the total elevation increase throughout the run.
* **total_descent**: the total elevation decrease throughout the run.
* **track_line**: A MultiLineString object containing LineStrings that represent each continous segment between pauses.

```{python}
# calculate number of pauses, where a pause is defined as dt > 1 second
num_pauses = len(gdf.loc[gdf['dt'] > timedelta(seconds=1)])

# calculate the total duration, defined as the time between starting and ending the activity
total_duration = gdf['dt'].sum()

# calculate the active duration, defined as the total time minus any pauses
active_duration = gdf.loc[gdf['dt'] == timedelta(seconds=1), 'dt'].sum()

# calculate total distance, excluding pauses
total_distance_miles = gdf.loc[(gdf['dt'] == timedelta(seconds=1)), 'dx'].sum() / 1609

# calculate average pace, exclude any pace over 10 min/mi since those are not representative of actual running
average_pace = gdf.loc[gdf["pace (min/mi)"] < 10, "pace (min/mi)"].mean()

# calculate total ascent, excluding pauses
total_ascent = gdf.loc[(gdf['dt'] == timedelta(seconds=1)), 'elevation'].diff().loc[gdf['elevation'].diff() > 0].sum()

# calculate total descent, excluding pauses
total_descent = gdf.loc[(gdf['dt'] == timedelta(seconds=1)), 'elevation'].diff().loc[gdf['elevation'].diff() < 0].sum()

# split each pause segment into a LineString within a MultiLineString
fixed_track_line = shapely.MultiLineString([shapely.LineString(group['geometry']) for _, group in gdf.groupby('pause_segment')])
```

```{python}
#| echo: false
print(f"Number of Pauses: {num_pauses}")
print(f"Total Duration: {total_duration}")
print(f"Active Duration: {active_duration}")
print(f"Total Distance (miles): {total_distance_miles}")
print(f"Average Pace (min/mi): {average_pace}")
print(f"Total Ascent (m): {total_ascent}")
print(f"Total Descent (m): {total_descent}")
print("")
print("Fixed Track Line:")
display(fixed_track_line)
```

Now I will apply these GPX data extraction steps to each GPX file, and add the resulting summary statistics and fixed track line to our master dataframe.

```{python}
#| echo: false
print("Updated Master Dataframe:")
df_tracks = gpd.read_parquet("data/intermediate/track_info_unagg.parquet")
display(df_tracks.sample(10).sort_values("track_file_datetime"))
print(f"Dataframe Length: {len(df_tracks)} Rows")
```

#### 2.4.4 Activity Recombination
Sometimes, I chose to record a workout all in the same recorded activity, and other times I broke it into several recorded activities. To be able to effectively cluster routes, I need to standardize this. I am going to flatten all activities recorded on the same day into one workout entry with one combined GPX track. This will also fix any cases where I accidently ended an activity mid-run and had to start another. However, I will have to take special care to separate out doubles. During the season, we would run twice on some days, in the morning and the afternoon.

First, I will identify all dates with more than one recorded activity.
```{python}
# isolate dates with multiple runs for further processing
counts = df_tracks[["track_file_date", "start_datetime"]].groupby("track_file_date").agg("count")
multple_dates = counts.loc[counts["start_datetime"] > 1].index
# dataframe with single-run dates
df_tracks_singles = df_tracks.loc[~df_tracks['track_file_date'].isin(multple_dates)]
# dataframe with multiple-run dates
df_tracks_multiples = df_tracks.loc[df_tracks['track_file_date'].isin(multple_dates)]
```

Next, I need to find a way to identify doubles. Let's look at the distribution of the time between activities for all of the days with more than one recorded activity. To do this I will group all the workouts by their date and calculate the time between same-day workouts.
```{python}
#| echo: false
# plots exploring doubles
diff_list = []
for group_name, group in df_tracks_multiples.groupby("track_file_date"):
    diff_list += list(group["start_datetime"].diff().apply(lambda x: x.total_seconds()/60).values[1::])
diff_list = np.array(diff_list) / 60

fig, ax = plt.subplots(2, 1, figsize=(10, 8), sharex=True)
sns.violinplot(diff_list, ax=ax[0], orient='h')
cts, bins, patches = ax[1].hist(diff_list, bins=24)
for c, left, right in zip(cts, bins[:-1], bins[1:]):
    center = (left + right) / 2
    ax[1].text(center, c, f'{int(c)}', ha='center', va='bottom')
ax[0].axvline(3, c='k', ls='dotted')
ax[1].axvline(3, c='k', ls='dotted')
ax[0].set_title("Bimodal Distribution of Time Between Same-day Activities")

plt.tight_layout()
plt.show()
```

There is a excellently clear bimodal distribution. The mode around zero corresponds to the workout activities that should be aggregated together, and the mode around nine hours corresponds to doubles. I have marked three hours as an appropriate threshold. For the two activities just under 4 hours, I manually checked and they are doubles. Now, I will go through each date group, if there is a double, I will keep it separate, and then aggregate the other activities into one.

```{python}
def agg_track_lines(series):
    lines = []
    for mline in series:
        for line in mline.geoms:
            lines.append(line)
    return shapely.MultiLineString(lines)

rows = []
agg_dict = {
    "track_file": 'sum',
    "track_file_datetime": 'min',
    "day_of_week": 'first',
    "start_datetime": 'first',
    "end_datetime": 'last',
    "year": 'first',
    "season": 'first',
    "num_pauses": 'sum',
    "total_duration": 'sum',
    "active_duration": 'sum',
    "total_distance (mi)": 'sum',
    "average_pace (min/mi)": 'mean',
    "total_ascent (m)": 'sum',
    "total_descent (m)": 'sum',
    "start_point": 'first',
    "end_point": 'last',
    "track_line": agg_track_lines
}

for group_name, group in df_tracks_multiples.groupby("track_file_date"):
    split = group['start_datetime'].diff().apply(lambda x: x.total_seconds()/3600) > 3
    if split.sum() > 0:
        # add condensed first session
        temp = group[:split.argmax()].groupby("track_file_date").agg(agg_dict).reset_index()
        temp["num_pauses"] = temp["num_pauses"] + len(group[:split.argmax()]) - 1
        rows.append(temp)

        # add condensed second session
        temp = group[split.argmax():].groupby("track_file_date").agg(agg_dict).reset_index()
        temp["num_pauses"] = temp["num_pauses"] + len(group[split.argmax():]) - 1
        rows.append(temp)
    else:
        # add condensed session
        rows.append(group.groupby("track_file_date").agg(agg_dict).reset_index())

df_tracks_multiples_combined = gpd.GeoDataFrame(pd.concat(rows), geometry="track_line", crs="EPSG:4326")
df_tracks_multiples_combined["start_point"] = gpd.GeoSeries(df_tracks_multiples_combined["end_point"], crs=df_tracks_multiples_combined.crs)
df_tracks_multiples_combined["end_point"] = gpd.GeoSeries(df_tracks_multiples_combined["end_point"], crs=df_tracks_multiples_combined.crs)
```

```{python}
#| echo: false
print("Table with multiples combined")
display(df_tracks_multiples_combined.head(5))
print(f"Dataframe Length: {len(df_tracks_multiples_combined)} Rows")
```

```{python}
#| echo: false
df_tracks = pd.concat([df_tracks_singles, df_tracks_multiples_combined]).sort_values("track_file_datetime").reset_index(drop=True)
print("Current Master Dataframe:")
display(df_tracks.head(5))
print(f"Dataframe Length: {len(df_tracks)} Rows")
```

#### 2.4.5 Region Assignment
The vast majority of runs take place somewhere within St. Charles (there are some in other regions of the state and country from trips), and within St. Charles they form some natural clusters.

```{python}
#| echo: false
df_tracks = gpd.read_parquet("data/cleaned/track_info.parquet")
df_tracks_stc = df_tracks[df_tracks["region"] != "Other"]
regions = gpd.read_file("data/raw/regions.geojson")

fig, ax = plt.subplots(figsize=(8, 8))
regions[6::].to_crs(3857).plot(ax=ax, ls='dashed', edgecolor='k', lw=1, facecolor='none')
df_tracks_stc.set_geometry("start_point").to_crs(3857).plot(ax=ax, markersize=2)
cx.add_basemap(ax, source=cx.providers.CartoDB.Voyager)
plt.show()
```

I identified six regions within St. Charles that are typical starting places for runs and added this variable to our master dataframe.

```{python}
#| echo: false
fig, ax = plt.subplots(figsize=(8, 8))
regions.to_crs(3857).plot(ax=ax, ls='dashed', edgecolor='k', lw=1, facecolor='none')
df_tracks_stc.set_geometry("start_point").to_crs(3857).plot("region", ax=ax, legend=True, marker='o', s=2)
cx.add_basemap(ax, source=cx.providers.CartoDB.Voyager)
plt.show()
```

## 3. Route Clustering
<a id="route_clustering"></a>
Routes are segments of tracks that show up time and time again across the dataset. A single run may contain more than one route, since sometimes routes are chained together.

I am going to use an unsupervised machine learning model to identify runs that traverse the same route. From there, I will manually assign each route its name. Not every run will be a known route, sometimes a route was not run more than a once or twice.

The model needs to cluster routes based on the GPS trajectory. We need to coax the GPS trajectory into a set of feature variables. To do this, we are going to spatially index the trajectory using H3 cells. This maps each latitude/longitude coordinate pair onto a hexagonal grid, such that each coordinate pair returns a cell ID. There are several different grid resolutions, and 11 seems to work well, it corresponds to an edge length of 28 meters. This step converts our sequence of continuous coordinates into a sequence of discrete cells. The next step is to vectorize the sequence using term-frequency-inverse-document-frequency vectorization.

These steps are all wrapped inside of sci-kit learn pipelines and custom transformers. The final step is to run the clustering algorithm, HDBSCAN. Here is the architecture of the model:
```{python}
cell_res = 11
min_cluster_size = 4

track_cells_pipeline = Pipeline(
    steps=[
        ('h3', TrackCellTransformer(cell_res=cell_res)),
        ('vectorizor', TfidfVectorizer()),
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ('track_line_cells', track_cells_pipeline, ["track_line"]),
    ],
    remainder='drop'
)

model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('estimator', HDBSCAN(metric='cosine', min_cluster_size=min_cluster_size)),
    ]
)
```

Let's fit the model and look at the results.
```{python}
#| warning: false
_ = model.fit(df_tracks_stc)
```

```{python}
#| echo: false
df_tracks_stc['route_label'] = model.named_steps['estimator'].labels_
df_tracks_stc['route_probability'] = model.named_steps['estimator'].probabilities_

num_groups = len(df_tracks_stc['route_label'].value_counts())
print(f"Total Runs: {len(df_tracks_stc)}")
print(f"Number of Clusters: {num_groups}")
num_runs_without_group = len(df_tracks_stc.loc[df_tracks_stc['route_label'] == -1])
print(f"Number of Unclustered Runs: {num_runs_without_group}")
mean_group_size = df_tracks_stc['route_label'].loc[df_tracks_stc['route_label'] != -1].value_counts().mean()
print(f"Mean Cluster Size: {mean_group_size:.2f}")
median_group_size = df_tracks_stc['route_label'].loc[df_tracks_stc['route_label'] != -1].value_counts().median()
print(f"Median Cluster Size: {median_group_size}")

sns.violinplot(df_tracks_stc['route_label'].loc[df_tracks_stc['route_label'] != -1].value_counts())
plt.title("Number of Runs per Route Cluster")
plt.show()
sns.violinplot(df_tracks_stc['route_probability'].loc[df_tracks_stc['route_label'] != -1])
plt.title("Distribution of Cluster Probabilities")
plt.show()
```

I complied a report of the clustering into a [PDF](results/multipage_plots.pdf) showing all the clusters and all the routes belonging to each cluster. I used this to manually label each route with its name, and then merged these names into our master dataframe.

```{python}
#| echo: false
df_routes = pd.read_csv("data/raw/routes.csv")
df_tracks_stc = pd.merge(df_tracks_stc, df_routes[["route_label", "route_type", "route_name"]], on="route_label", how="left").drop(columns=["route_label"])
df_tracks_stc['route_type'] = df_tracks_stc['route_type'].fillna("Unknown")
df_tracks_stc['route_name'] = df_tracks_stc['route_name'].fillna("Unknown")

print("Current Master Dataframe:")
display(df_tracks_stc.head(5))
print(f"Dataframe Length: {len(df_tracks)} Rows")

plt.figure(figsize=(12, 5))
plt.bar(df_tracks_stc.loc[df_tracks_stc['route_name'] != "Unknown", 'route_name'].value_counts().index, df_tracks_stc.loc[df_tracks_stc['route_name'] != "Unknown", 'route_name'].value_counts().values)
plt.xticks(rotation=90, fontsize=8)
plt.title("Route Distribution")
plt.show()
```

## 4. Next Steps
<a id="next_steps"></a>
My primary goal is to somehow use PyTorch to create a neural network that does something cool. I'm having trouble articulating exactly what I want the end results to look like, but I will try to outline some of what I am thinking.

- One desire I have is to give every run a label based on what type of run it is, like Normal Run, Long Run, Tempo Workout, Track Workout, Hill Workout, or Fartlek Workout. This would probably be closely coupled with the route and I'm not sure how to approach that.
- Right now, I have assigned route names based on the clustering results. Out of 803 total runs, the 754 that are located in St. Charles were put through the clustering model. 509 were given route labels, and 245 were labeled as unknown.
- In addition to routes, I think it could be interesting to look at more specific route segments and identifying all the runs that contain a given segment. This would be a use for a Transformer-based deep model. I'm having trouble seeing what the data structure for this might look like.
- The route framework has limitations too. Some runs are more *adventurous*, and do not follow the same exact trajectory, but may still be clustered in a certain region, like a park. This is sort of accounted for in the region variable I already have.
- For runs that are workouts, the workout typically contains a warmup, one or more workout segments, and a cooldown. It would be interesting to be able to break these apart and look at specific workout stats, and also examine routes and segments for warmups, workouts, and cooldowns.


Route Decomposition
GPS points
        │
        ▼
H3 cells
        │
        ▼
Embedding layer
        │
        ▼
Transformer
        │
        ▼
Segment label or unknown segment for each point, compressing duplicates
        │                           │
        ▼                           ▼
Route Segments: S1 → S2 → S4    Route Segments: S1 → Unknown
        |                           │ 
        ▼                           ▼
Route lookup                    Region Clustering
        │                           │
        ▼                           ▼
Route: Dog Leg                 Route: LeRoy Oakes