<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Cross Country Workout Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="showcase_files/libs/clipboard/clipboard.min.js"></script>
<script src="showcase_files/libs/quarto-html/quarto.js"></script>
<script src="showcase_files/libs/quarto-html/popper.min.js"></script>
<script src="showcase_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="showcase_files/libs/quarto-html/anchor.min.js"></script>
<link href="showcase_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="showcase_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="showcase_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="showcase_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="showcase_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><strong>Cross Country Workout Data</strong></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Created by Ryan Sponzilli</em></p>
<section id="table-of-contents" class="level2">
<h2 class="anchored" data-anchor-id="table-of-contents">Table of Contents</h2>
<ul>
<li><a href="#1-introduction">1. Introduction</a>
<ul>
<li><a href="#11-goals">1.1 Goals</a></li>
</ul></li>
<li><a href="#2-data-cleaning">2. Data Cleaning</a>
<ul>
<li><a href="">2.1 GPX File List</a>
<ul>
<li><a href="">2.1.1 Parse Filename</a></li>
<li><a href="">2.1.2 Filter Time Period</a></li>
<li><a href="">2.1.3 Year &amp; Season Bucketing</a></li>
</ul></li>
<li><a href="">2.2 Workouts XML</a>
<ul>
<li><a href="">2.2.1 Filter Time Period</a></li>
<li><a href="">2.2.2 Filter Activity Type</a></li>
</ul></li>
<li><a href="">2.3 Merge GPX File List with Workout Data</a></li>
<li><a href="">2.4 GPX Track Data Extraction</a>
<ul>
<li><a href="">2.4.3 Statistics</a></li>
<li><a href="">2.4.2 Pause Detection</a></li>
</ul></li>
</ul></li>
<li><a href="#3-route-classification">3. Route Classification</a>
<ul>
<li><a href="">4.1 Unsupervised Route Clustering</a></li>
<li><a href="">4.2 Creating a Route Library</a></li>
<li><a href="">4.2 Supervised Route Clustering</a></li>
</ul></li>
<li><a href="#4-run-type-classification">4. Run Type Classification</a>
<ul>
<li><a href="">5.1 Run Type Overview</a></li>
<li><a href="">5.2 Flagging Doubles</a></li>
<li><a href="">5.3 Fixing Accidental Splits</a></li>
<li><a href="">5.4 Grouping Workouts</a></li>
</ul></li>
<li><a href="#5-analysis">5. Analysis</a></li>
<li><a href="#6-summary">6. Summary</a></li>
</ul>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p>I ran cross country and track all four years that I was in high school, and I recorded every single run on my Apple Watch. I believe that this is a very unique trove of data that has the potential to be very interesting and very personal.</p>
<p>I obtained the raw data by exporting my Apple Health data. This export gave me a 2.23 GB <code>.xml</code> file and a folder containing 1,232 <code>.gpx</code> files.</p>
<p>I have constructed this document to explain each decision I made while working with this data and present the results. My work on this project was very nonlinear and experimental, as is anything that is being figured out for the first time, so please be aware that I have taken my final process and presented it in a logical and linear order here. Note that not all of the code is visible, and that the code that is made visible is meant to illustrate the processes.</p>
<section id="goals" class="level3">
<h3 class="anchored" data-anchor-id="goals">1.1 Goals</h3>
<ul>
<li>Learn how to work with geospatial data and tools:
<ul>
<li>Learn how to manipulate geospatial data with the <code>geopandas</code> library.</li>
<li>Learn how to create effective visualizations of geospatial data.</li>
</ul></li>
<li>Develop a data pipeline to ingest the raw data and output a processed dataset ready for analysis and visualization:
<ul>
<li>Use machine learning techniques to perform route geoclustering and route decomposition.</li>
<li>Categorize runs into specific types (e.g., workouts, long runs, normal runs).</li>
<li>Thoroughly document every decision and assumption made while processing the data.</li>
</ul></li>
<li>Analyze the data to create visually appealing and informative maps and charts:
<ul>
<li>Understand the geographic distribution of my runs.</li>
<li>Understand my training regimen and how it evolved over time.</li>
<li>Understand how I improved over my four years.</li>
</ul></li>
</ul>
<!-- The `.xml` file contains a `Record` tag, which contains a data record for a health statistic, such as *ActiveEnergyBurned*, *HeartRate*, or *EnvironmentalAudioExposure*. This will be useful for getting fitness statistics, such as heart rate, VO2 max, and calories burned. -->
</section>
</section>
<section id="data-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning">2. Data Cleaning</h2>
<p>The raw data must be converted into a convenient form, have certain constraints applied, and new features derived. As shown above, the raw data is spread across several different sources which must be integrated together.</p>
<section id="gpx-file-list" class="level3">
<h3 class="anchored" data-anchor-id="gpx-file-list">2.1 GPX File List</h3>
<p>The first piece of this puzzle is to assemble a list of all the GPX files. I will start by obtaining all of the filepaths.</p>
<div id="78ac789d" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>Here are the filepaths:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">track_file</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">703</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">230</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">741</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataframe Length: 1232 Rows
Example file name: route_2020-10-06_3.55pm.gpx</code></pre>
</div>
</div>
<p>Each file name contains a date and time (referred to as a datetime). This datetime corresponds to the creation of the file. This is an important piece of information, so I will extract it from the file name and put it in its own column. It will also be useful to have a column with the date only.</p>
<div id="4d02629d" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># parse track file dates</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df_tracks[<span class="st">"track_file_datetime"</span>] <span class="op">=</span> df_tracks[<span class="st">"track_file"</span>].<span class="bu">apply</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> x: datetime.strptime(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>        x.split(<span class="st">"/"</span>)[<span class="op">-</span><span class="dv">1</span>].removeprefix(<span class="st">"route_"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>        .removesuffix(<span class="st">".gpx"</span>), <span class="st">"%Y-%m-</span><span class="sc">%d</span><span class="st">_%I.%M%p"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        .replace(tzinfo<span class="op">=</span>ZoneInfo(<span class="st">"America/Chicago"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>df_tracks[<span class="st">"track_file_date"</span>] <span class="op">=</span> df_tracks[<span class="st">"track_file_datetime"</span>].dt.date</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="33299cf7" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>Updated table with dates extracted:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">track_file</th>
<th data-quarto-table-cell-role="th">track_file_datetime</th>
<th data-quarto-table-cell-role="th">track_file_date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">611</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2021-10-16 11:47:00-05:00</td>
<td>2021-10-16</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1039</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2022-06-29 07:17:00-05:00</td>
<td>2022-06-29</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">461</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2020-06-29 07:28:00-05:00</td>
<td>2020-06-29</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataframe Length: 1232 Rows</code></pre>
</div>
</div>
<p>The next thing I want to do is to filter for only the runs that occurred while I was in high school. Additionally, I want to bucket the runs into each year of high school and each season of the year. To do this, I went back into my calendar and manually created a table with the necessary information.</p>
<div id="32fa0242" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>Minimum Date: 2019-06-10 00:00:00-05:00
Maximum Date 2023-05-16 00:00:00-05:00
Year and Seasons Buckets:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">season</th>
<th data-quarto-table-cell-role="th">start_date</th>
<th data-quarto-table-cell-role="th">end_date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Freshman</td>
<td>Summer Training</td>
<td>2019-06-10 00:00:00-05:00</td>
<td>2019-08-12 00:00:00-05:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Freshman</td>
<td>XC Season</td>
<td>2019-08-12 00:00:00-05:00</td>
<td>2019-11-08 00:00:00-06:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Freshman</td>
<td>Winter Training</td>
<td>2019-11-08 00:00:00-06:00</td>
<td>2020-01-27 00:00:00-06:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Freshman</td>
<td>Track Season</td>
<td>2020-01-27 00:00:00-06:00</td>
<td>2020-05-02 00:00:00-05:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Sophomore</td>
<td>Summer Training</td>
<td>2020-05-02 00:00:00-05:00</td>
<td>2020-08-10 00:00:00-05:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Sophomore</td>
<td>XC Season</td>
<td>2020-08-10 00:00:00-05:00</td>
<td>2020-10-19 00:00:00-05:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Sophomore</td>
<td>Winter Training</td>
<td>2020-10-19 00:00:00-05:00</td>
<td>2021-04-05 00:00:00-05:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>Sophomore</td>
<td>Track Season</td>
<td>2021-04-05 00:00:00-05:00</td>
<td>2021-06-10 00:00:00-05:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>Junior</td>
<td>Summer Training</td>
<td>2021-06-10 00:00:00-05:00</td>
<td>2021-08-09 00:00:00-05:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>Junior</td>
<td>XC Season</td>
<td>2021-08-09 00:00:00-05:00</td>
<td>2021-10-25 00:00:00-05:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>Junior</td>
<td>Winter Training</td>
<td>2021-10-25 00:00:00-05:00</td>
<td>2022-01-31 00:00:00-06:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>Junior</td>
<td>Track Season</td>
<td>2022-01-31 00:00:00-06:00</td>
<td>2022-04-28 00:00:00-05:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>Senior</td>
<td>Summer Training</td>
<td>2022-04-28 00:00:00-05:00</td>
<td>2022-08-08 00:00:00-05:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>Senior</td>
<td>XC Season</td>
<td>2022-08-08 00:00:00-05:00</td>
<td>2022-11-06 00:00:00-05:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>Senior</td>
<td>Winter Training</td>
<td>2022-11-06 00:00:00-05:00</td>
<td>2023-01-30 00:00:00-06:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>Senior</td>
<td>Track Season</td>
<td>2023-01-30 00:00:00-06:00</td>
<td>2023-05-16 00:00:00-05:00</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><br></p>
<p>Now I will apply the minimum and maximum date constraints, and apply the bucketing.</p>
<div id="87f49e5e" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bucket dates into seasons</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>df_tracks <span class="op">=</span> (</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    df_tracks.loc[(df_tracks[<span class="st">"track_file_datetime"</span>] <span class="op">&gt;=</span> seasons.MIN_DATE) <span class="op">&amp;</span> (df_tracks[<span class="st">"track_file_datetime"</span>] <span class="op">&lt;=</span> seasons.MAX_DATE)]</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    .sort_values(<span class="st">"track_file_datetime"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    .reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>df_tracks[<span class="st">"year"</span>] <span class="op">=</span> df_tracks[<span class="st">"track_file_datetime"</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: seasons.bucket_date(x)[<span class="dv">0</span>])</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>df_tracks[<span class="st">"season"</span>] <span class="op">=</span> df_tracks[<span class="st">"track_file_datetime"</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: seasons.bucket_date(x)[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="e37e2739" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>Updated table with dates bucketed:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">track_file</th>
<th data-quarto-table-cell-role="th">track_file_datetime</th>
<th data-quarto-table-cell-role="th">track_file_date</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">season</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">148</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-10-15 15:22:00-05:00</td>
<td>2019-10-15</td>
<td>Freshman</td>
<td>XC Season</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">74</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-09-07 10:23:00-05:00</td>
<td>2019-09-07</td>
<td>Freshman</td>
<td>XC Season</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1066</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2023-03-06 06:25:00-06:00</td>
<td>2023-03-06</td>
<td>Senior</td>
<td>Track Season</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataframe Length: 1128 Rows</code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="workouts-xml" class="level3">
<h3 class="anchored" data-anchor-id="workouts-xml">2.2 Workouts XML</h3>
<p>The <code>.xml</code> file contains a <code>Workout</code> tag, which contains a data record for individual workouts. Not much useful information is provided in these records, just dates, a duration, and the type of activity. The type of activity is the most important field. Since the GPX tracks do not specify what activity they contain, I will need to link them to these records to identifiy which ones correspond to runs, and not to walks, bike rides, or hikes.</p>
<div id="ff871ccd" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>Sample of 3 "Workout" records:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">workoutActivityType</th>
<th data-quarto-table-cell-role="th">duration</th>
<th data-quarto-table-cell-role="th">durationUnit</th>
<th data-quarto-table-cell-role="th">sourceName</th>
<th data-quarto-table-cell-role="th">sourceVersion</th>
<th data-quarto-table-cell-role="th">creationDate</th>
<th data-quarto-table-cell-role="th">startDate</th>
<th data-quarto-table-cell-role="th">endDate</th>
<th data-quarto-table-cell-role="th">device</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">886</td>
<td>HKWorkoutActivityTypeRunning</td>
<td>2.488188584645589</td>
<td>min</td>
<td>Ryan’s Apple&nbsp;Watch</td>
<td>7.5</td>
<td>2021-10-04 16:38:26 -0600</td>
<td>2021-10-04 15:25:25 -0600</td>
<td>2021-10-04 16:38:24 -0600</td>
<td>&lt;&lt;HKDevice: 0x3000bd450&gt;, name:Apple Watch, ma...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1110</td>
<td>HKWorkoutActivityTypeRunning</td>
<td>17.75</td>
<td>min</td>
<td>Strava</td>
<td>34212</td>
<td>2022-09-24 17:00:38 -0600</td>
<td>2022-09-24 13:36:24 -0600</td>
<td>2022-09-24 13:54:09 -0600</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">512</td>
<td>HKWorkoutActivityTypeRunning</td>
<td>30.04409821033478</td>
<td>min</td>
<td>Ryan’s Apple&nbsp;Watch</td>
<td>7.0.2</td>
<td>2020-11-10 14:13:33 -0600</td>
<td>2020-11-10 13:24:28 -0600</td>
<td>2020-11-10 14:13:32 -0600</td>
<td>&lt;&lt;HKDevice: 0x3003f5db0&gt;, name:Apple Watch, ma...</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataframe Length: 1460 Rows</code></pre>
</div>
</div>
<p>To separate runs from hikes, walks, and bike rides, I need to cross reference each GPX file with its corresponding entry in the “Workouts” table from the <code>.xml</code> file. I will go ahead and filter the time period to the minimum and maximum dates. I also want to select only workouts that came from my Apple Watch. I need to exclude any Strava runs since I do not have any GPX files associated with them.</p>
<div id="92b0d539" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># parse data types</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>df_workouts[<span class="st">'creationDate'</span>] <span class="op">=</span> pd.to_datetime(df_workouts[<span class="st">'creationDate'</span>])</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>df_workouts[<span class="st">'startDate'</span>] <span class="op">=</span> pd.to_datetime(df_workouts[<span class="st">'startDate'</span>])</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>df_workouts[<span class="st">'endDate'</span>] <span class="op">=</span> pd.to_datetime(df_workouts[<span class="st">'endDate'</span>])</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>df_workouts[<span class="st">'duration'</span>] <span class="op">=</span> df_workouts[<span class="st">'duration'</span>].astype(<span class="bu">float</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># filter time period</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>df_workouts <span class="op">=</span> df_workouts.loc[(df_workouts[<span class="st">'startDate'</span>] <span class="op">&gt;=</span> pd.to_datetime(seasons.MIN_DATE, utc<span class="op">=</span><span class="va">True</span>)) <span class="op">&amp;</span> (df_workouts[<span class="st">'startDate'</span>] <span class="op">&lt;=</span> pd.to_datetime(seasons.MAX_DATE, utc<span class="op">=</span><span class="va">True</span>))]</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># get relevant data</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>df_workouts <span class="op">=</span> df_workouts.loc[df_workouts[<span class="st">'sourceName'</span>] <span class="op">!=</span> <span class="st">"Strava"</span>]</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>df_workouts <span class="op">=</span> df_workouts[[<span class="st">"workoutActivityType"</span>, <span class="st">"creationDate"</span>, <span class="st">"startDate"</span>, <span class="st">"endDate"</span>, <span class="st">"duration"</span>, <span class="st">"durationUnit"</span>]].rename(columns<span class="op">=</span>{<span class="st">"creationDate"</span>: <span class="st">"creation_datetime"</span>, <span class="st">"startDate"</span>: <span class="st">"start_datetime"</span>, <span class="st">"endDate"</span>: <span class="st">"end_datetime"</span>})</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>df_workouts <span class="op">=</span> df_workouts.sort_values(<span class="st">"start_datetime"</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="71e4a30d" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>Workouts table after parsing:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">workoutActivityType</th>
<th data-quarto-table-cell-role="th">creation_datetime</th>
<th data-quarto-table-cell-role="th">start_datetime</th>
<th data-quarto-table-cell-role="th">end_datetime</th>
<th data-quarto-table-cell-role="th">duration</th>
<th data-quarto-table-cell-role="th">durationUnit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">15</td>
<td>HKWorkoutActivityTypeRunning</td>
<td>2019-06-26 06:11:39-06:00</td>
<td>2019-06-26 05:52:19-06:00</td>
<td>2019-06-26 06:11:27-06:00</td>
<td>18.503048</td>
<td>min</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">736</td>
<td>HKWorkoutActivityTypeHiking</td>
<td>2021-06-23 10:53:46-06:00</td>
<td>2021-06-23 10:25:40-06:00</td>
<td>2021-06-23 10:53:44-06:00</td>
<td>28.067195</td>
<td>min</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1190</td>
<td>HKWorkoutActivityTypeRunning</td>
<td>2023-02-17 15:54:09-06:00</td>
<td>2023-02-17 15:04:59-06:00</td>
<td>2023-02-17 15:48:17-06:00</td>
<td>38.233994</td>
<td>min</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataframe Length: 1268 Rows</code></pre>
</div>
</div>
</section>
<section id="merge-gpx-file-list-with-workouts-xml" class="level3">
<h3 class="anchored" data-anchor-id="merge-gpx-file-list-with-workouts-xml">2.3 Merge GPX File List with Workouts XML</h3>
<p>Both tables are prepared, but there is one obstacle remaining to merging them together. The <code>track_file_datetime</code> column in the GPX file dataframe refers to a creation time, so in the merge, we will reference this column to the <code>creation_datetime</code> column in the Workouts dataframe. However, due to whatever reason, these datetimes will not line up identically, they may be offset by several seconds or minutes. To fix this, I will iterate through each <code>track_file_datetime</code> in the GPX track dataframe and locate the closest match in the Workouts dataframe, and store this value in a new temporary column. Then I will merge on this temporary column, and drop any rows that are not running workouts.</p>
<div id="60fc7acf" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>Merged Dataframes:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">track_file</th>
<th data-quarto-table-cell-role="th">track_file_datetime</th>
<th data-quarto-table-cell-role="th">track_file_date</th>
<th data-quarto-table-cell-role="th">day_of_week</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">season</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-06-10 07:46:00-05:00</td>
<td>2019-06-10</td>
<td>Monday</td>
<td>Freshman</td>
<td>Summer Training</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-06-11 07:32:00-05:00</td>
<td>2019-06-11</td>
<td>Tuesday</td>
<td>Freshman</td>
<td>Summer Training</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-06-12 07:35:00-05:00</td>
<td>2019-06-12</td>
<td>Wednesday</td>
<td>Freshman</td>
<td>Summer Training</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataframe Length: 1033 Rows</code></pre>
</div>
</div>
<p>Notice that we dropped from 1268 rows to 1033 rows. We have successfully removed all of the non-running GPX tracks from the dataframe.</p>
<p><br></p>
</section>
<section id="gpx-track-data-extraction" class="level3">
<h3 class="anchored" data-anchor-id="gpx-track-data-extraction">2.4 GPX Track Data Extraction</h3>
<p>Now that we have a clean dataset containing all of the runs, it’s time to look inside the GPX files themselves. For each GPX file, the data points are a time series sampled once per second where each timestamp has an associated latitude/longitude coordinate pair and an elevation. We can extract a lot of information from just this information.</p>
<p>A single <code>.gpx</code> file can contain multiple data layers:</p>
<div id="64d5c6b2" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>GPX File Layers:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">geometry_type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>waypoints</td>
<td>Point</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>routes</td>
<td>LineString</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>tracks</td>
<td>MultiLineString</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>route_points</td>
<td>Point</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>track_points</td>
<td>Point</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><br></p>
<p>However, only two of the layers contain any data. These are the <code>tracks</code> layer and the <code>track_points</code> layer. I can load these individually using <code>geopandas.read_file()</code>. Most of the columns do not contain any data, but what really matters is the <code>geometry</code> column.</p>
<div id="b85ded97" class="cell" data-execution_count="14">
<div class="cell-output cell-output-stdout">
<pre><code>"tracks" Layer:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">cmt</th>
<th data-quarto-table-cell-role="th">desc</th>
<th data-quarto-table-cell-role="th">src</th>
<th data-quarto-table-cell-role="th">link1_href</th>
<th data-quarto-table-cell-role="th">link1_text</th>
<th data-quarto-table-cell-role="th">link1_type</th>
<th data-quarto-table-cell-role="th">link2_href</th>
<th data-quarto-table-cell-role="th">link2_text</th>
<th data-quarto-table-cell-role="th">link2_type</th>
<th data-quarto-table-cell-role="th">number</th>
<th data-quarto-table-cell-role="th">type</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Route 2020-10-06 3:55pm</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>NaN</td>
<td>None</td>
<td>MULTILINESTRING ((-88.27857 41.92811, -88.2786...</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><br></p>
<div id="c864c08b" class="cell" data-execution_count="15">
<div class="cell-output cell-output-stdout">
<pre><code>"track_points" Layer:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">track_fid</th>
<th data-quarto-table-cell-role="th">track_seg_id</th>
<th data-quarto-table-cell-role="th">track_seg_point_id</th>
<th data-quarto-table-cell-role="th">ele</th>
<th data-quarto-table-cell-role="th">time</th>
<th data-quarto-table-cell-role="th">magvar</th>
<th data-quarto-table-cell-role="th">geoidheight</th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">cmt</th>
<th data-quarto-table-cell-role="th">desc</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">sym</th>
<th data-quarto-table-cell-role="th">type</th>
<th data-quarto-table-cell-role="th">fix</th>
<th data-quarto-table-cell-role="th">sat</th>
<th data-quarto-table-cell-role="th">hdop</th>
<th data-quarto-table-cell-role="th">vdop</th>
<th data-quarto-table-cell-role="th">pdop</th>
<th data-quarto-table-cell-role="th">ageofdgpsdata</th>
<th data-quarto-table-cell-role="th">dgpsid</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>241.046722</td>
<td>2020-10-06 20:21:07+00:00</td>
<td>NaN</td>
<td>NaN</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>...</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>POINT (-88.27857 41.92811)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>240.653961</td>
<td>2020-10-06 20:21:07+00:00</td>
<td>NaN</td>
<td>NaN</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>...</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>POINT (-88.27862 41.9281)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0</td>
<td>0</td>
<td>2</td>
<td>240.572311</td>
<td>2020-10-06 20:21:08+00:00</td>
<td>NaN</td>
<td>NaN</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>...</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>POINT (-88.27863 41.9281)</td>
</tr>
</tbody>
</table>

<p>3 rows × 27 columns</p>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataframe Length: 2007 Rows</code></pre>
</div>
</div>
<p>The <code>track_points</code> layer is more useful, since it provides a more granular representation of the data. For each point, it gives a coordinate, timestamp, and elevation. These can be used to derive statistics such as elapsed distance, running pace, elevation change, and later, for route geoclustering.</p>
<div id="b9a8e314" class="cell" data-execution_count="16">
<div class="cell-output cell-output-stdout">
<pre><code>The track points plotted on a map:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="showcase_files/figure-html/cell-17-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Before we get into detecting pauses and deriving statistics, I will properly parse the <code>track_points</code> dataframe and extract two helper columns, <code>dt</code> and <code>dx</code>, describing the change in time and position, respectively, from one track point to the next.</p>
<div id="cfc3aa09" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># parse file</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>gdf <span class="op">=</span> gdf[[<span class="st">"time"</span>, <span class="st">"ele"</span>, <span class="st">"geometry"</span>]]</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>gdf[<span class="st">"time"</span>] <span class="op">=</span> pd.to_datetime(gdf[<span class="st">"time"</span>])</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>gdf <span class="op">=</span> gdf.rename(columns<span class="op">=</span>{<span class="st">"time"</span>: <span class="st">"datetime"</span>, <span class="st">"ele"</span>: <span class="st">"elevation"</span>})</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># create helper columns</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>gdf[<span class="st">'dt'</span>] <span class="op">=</span> gdf[<span class="st">"datetime"</span>].diff()</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>gdf_utm <span class="op">=</span> gdf.to_crs(gdf.estimate_utm_crs())</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>gdf[<span class="st">"dx"</span>] <span class="op">=</span> gdf_utm[<span class="st">"geometry"</span>].distance(gdf_utm[<span class="st">"geometry"</span>].shift())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="a3a8f419" class="cell" data-execution_count="18">
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">datetime</th>
<th data-quarto-table-cell-role="th">elevation</th>
<th data-quarto-table-cell-role="th">geometry</th>
<th data-quarto-table-cell-role="th">dt</th>
<th data-quarto-table-cell-role="th">dx</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2020-10-06 20:21:07+00:00</td>
<td>241.046722</td>
<td>POINT (-88.27857 41.92811)</td>
<td>NaT</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2020-10-06 20:21:07+00:00</td>
<td>240.653961</td>
<td>POINT (-88.27862 41.9281)</td>
<td>0 days 00:00:00</td>
<td>4.004974</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2020-10-06 20:21:08+00:00</td>
<td>240.572311</td>
<td>POINT (-88.27863 41.9281)</td>
<td>0 days 00:00:01</td>
<td>0.829222</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<section id="pause-detection" class="level4">
<h4 class="anchored" data-anchor-id="pause-detection">2.4.1 Pause Detection</h4>
<p>Before I can extract summary statistics, it is necessary to account for gaps in the data which can distort the statistics. Many runs contain pauses, where I manually paused the run to wait to cross the street, take a break, or for a rest between workout segments. In some cases, the pause may be extra long because I forgot to resume the run.</p>
<p>Left as-is, these pauses will result in calculating incorrect statistics like duration, distance, and pace. These also cause the map plots to interpolate the track line over the gap which looks funny and does not accurately reflect the run.</p>
<div id="e57a15d2" class="cell" data-execution_count="19">
<div class="cell-output cell-output-stdout">
<pre><code>Pauses lead to misleading maps like this one where I forgot to unpause the run:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="showcase_files/figure-html/cell-20-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Detecting pauses and splitting the track into segments will yield a more accurate plot:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="showcase_files/figure-html/cell-20-output-4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Each run is nominally sampled every second, so pauses can be detected by any gaps in the time series greater than 1 second. To be on the safe side, I will use a gap threshold of 5 seconds.</p>
<p>These are the required steps:</p>
<ol type="1">
<li>Locate indices of time-pauses in each run, with threshold of 5 seconds.</li>
<li>Split the data into segments along the located indices by creating an indicator column.</li>
<li>Remove segments less than 10 seconds, since these are mistakes with no meaningful value.</li>
</ol>
<div id="38cde0c4" class="cell" data-execution_count="20">
<div class="cell-output cell-output-stdout">
<pre><code>The rest of this section will continue using this track as an example:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="showcase_files/figure-html/cell-21-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="3d5c4ea6" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># split into segments at pause indices</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>pause_idx <span class="op">=</span> <span class="bu">list</span>(gdf.loc[gdf[<span class="st">'dt'</span>] <span class="op">&gt;</span> timedelta(seconds<span class="op">=</span><span class="dv">1</span>)].index)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>gdf[<span class="st">'pause_segment'</span>] <span class="op">=</span> <span class="va">None</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>segment_idx <span class="op">=</span> ([<span class="dv">0</span>] <span class="op">+</span> pause_idx <span class="op">+</span> [<span class="bu">len</span>(gdf)])</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(segment_idx) <span class="op">-</span> <span class="dv">1</span>):</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    gdf.loc[segment_idx[i]:segment_idx[i<span class="op">+</span><span class="dv">1</span>], <span class="st">'pause_segment'</span>] <span class="op">=</span> i</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># remove segments less than 10 seconds</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>gdf <span class="op">=</span> gdf.groupby(<span class="st">"pause_segment"</span>, group_keys<span class="op">=</span><span class="va">False</span>).<span class="bu">filter</span>(<span class="kw">lambda</span> x: <span class="bu">len</span>(x) <span class="op">&gt;</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="53c2d5ae" class="cell" data-execution_count="22">
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">datetime</th>
<th data-quarto-table-cell-role="th">elevation</th>
<th data-quarto-table-cell-role="th">geometry</th>
<th data-quarto-table-cell-role="th">dt</th>
<th data-quarto-table-cell-role="th">dx</th>
<th data-quarto-table-cell-role="th">pause_segment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">419</td>
<td>2020-10-06 20:28:16+00:00</td>
<td>238.655075</td>
<td>POINT (-88.29144 41.93125)</td>
<td>0 days 00:00:01</td>
<td>3.346932</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">647</td>
<td>2020-10-06 20:32:04+00:00</td>
<td>237.618317</td>
<td>POINT (-88.29613 41.92586)</td>
<td>0 days 00:00:01</td>
<td>3.593353</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1064</td>
<td>2020-10-06 20:39:01+00:00</td>
<td>232.248688</td>
<td>POINT (-88.30394 41.9215)</td>
<td>0 days 00:00:01</td>
<td>3.446336</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1400</td>
<td>2020-10-06 20:44:37+00:00</td>
<td>236.480652</td>
<td>POINT (-88.29428 41.9226)</td>
<td>0 days 00:00:01</td>
<td>3.562078</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1464</td>
<td>2020-10-06 20:45:41+00:00</td>
<td>237.072632</td>
<td>POINT (-88.29252 41.9233)</td>
<td>0 days 00:00:01</td>
<td>3.333834</td>
<td>2</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of Pauses Detected: 3</code></pre>
</div>
</div>
</section>
<section id="rolling-pace" class="level4">
<h4 class="anchored" data-anchor-id="rolling-pace">2.4.2 Rolling Pace</h4>
<p>Before moving on to calculating summary statistics, I need to create a column for the current pace. The pace is my speed, usually measured in minutes per mile, so it is calculated by <code>dt</code> / <code>dx</code>. To calculate the pace, I will use a rolling average from the last 10 seconds, and importantly doing this separately within each pause segment. A side effect of using a rolling window of 10 seconds is that you cannot calculate it for the first 10 seconds, so we fill simply backfill the pace for the first 10 seconds.</p>
<div id="3861a82d" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate pace for each pause segment separately</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> calculate_rolling_pace(gdf):</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># use a 10 second rolling window for calculating pace</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    gdf[<span class="st">"pace (min/mi)"</span>] <span class="op">=</span> (gdf[<span class="st">"dt"</span>].cumsum().dt.total_seconds() <span class="op">/</span> <span class="dv">60</span>).diff(<span class="dv">10</span>) <span class="op">/</span> (gdf[<span class="st">"dx"</span>].cumsum() <span class="op">/</span> <span class="dv">1609</span>).diff(<span class="dv">10</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># backfill nans that resulted from the rolling window</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    gdf[<span class="st">"pace (min/mi)"</span>] <span class="op">=</span> gdf[<span class="st">"pace (min/mi)"</span>].bfill()</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> gdf</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>gdf <span class="op">=</span> gdf.groupby(<span class="st">'pause_segment'</span>).<span class="bu">apply</span>(calculate_rolling_pace).reset_index().drop(columns<span class="op">=</span>[<span class="st">"level_1"</span>], errors<span class="op">=</span><span class="st">'ignore'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="1dbe9b61" class="cell" data-execution_count="24">
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">pause_segment</th>
<th data-quarto-table-cell-role="th">datetime</th>
<th data-quarto-table-cell-role="th">elevation</th>
<th data-quarto-table-cell-role="th">geometry</th>
<th data-quarto-table-cell-role="th">dt</th>
<th data-quarto-table-cell-role="th">dx</th>
<th data-quarto-table-cell-role="th">pace (min/mi)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">238</td>
<td>2</td>
<td>2020-10-06 20:25:21+00:00</td>
<td>234.204208</td>
<td>POINT (-88.28623 41.93257)</td>
<td>0 days 00:00:01</td>
<td>3.342227</td>
<td>8.246420</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">371</td>
<td>2</td>
<td>2020-10-06 20:27:34+00:00</td>
<td>237.681564</td>
<td>POINT (-88.29075 41.93235)</td>
<td>0 days 00:00:01</td>
<td>3.321780</td>
<td>8.447384</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">426</td>
<td>2</td>
<td>2020-10-06 20:28:29+00:00</td>
<td>238.461578</td>
<td>POINT (-88.29158 41.93087)</td>
<td>0 days 00:00:01</td>
<td>3.413861</td>
<td>7.949844</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1321</td>
<td>2</td>
<td>2020-10-06 20:43:24+00:00</td>
<td>234.448425</td>
<td>POINT (-88.29549 41.92116)</td>
<td>0 days 00:00:01</td>
<td>2.917278</td>
<td>8.634977</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1467</td>
<td>2</td>
<td>2020-10-06 20:45:50+00:00</td>
<td>236.681366</td>
<td>POINT (-88.29216 41.92328)</td>
<td>0 days 00:00:01</td>
<td>3.407324</td>
<td>7.973592</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="summary-statistics" class="level4">
<h4 class="anchored" data-anchor-id="summary-statistics">2.4.3 Summary Statistics</h4>
<p>I would like to extract a few summary statistics from each run merge them into our master dataframe. These include:</p>
<ul>
<li><strong>start_point</strong>: the first point in the run.</li>
<li><strong>end_point</strong>: the last point in the run.</li>
<li><strong>start_datetime</strong>: the first timestamp in the run.</li>
<li><strong>end_datetime</strong>: the last timestamp in the run.</li>
<li><strong>num_pauses</strong>: the number of pauses, where a pause is defined as a gap greater than five seconds.</li>
<li><strong>total_duration</strong>: the total time elapsed from starting the run to ending the run, including all pauses.</li>
<li><strong>active_duration</strong>: the total time elapsed from starting the run to ending the run, excluding all pauses.</li>
<li><strong>total_distance</strong>: the total distance run in miles, excluding distance covered during pauses.</li>
<li><strong>average_pace</strong>: the average pace during the run.</li>
<li><strong>total_ascent</strong>: the total elevation increase throughout the run.</li>
<li><strong>total_descent</strong>: the total elevation decrease throughout the run.</li>
<li><strong>track_line</strong>: A MultiLineString object containing LineStrings that represent each continous segment between pauses.</li>
</ul>
<div id="ae3a25ef" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate number of pauses, where a pause is defined as dt &gt; 1 second</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>num_pauses <span class="op">=</span> <span class="bu">len</span>(gdf.loc[gdf[<span class="st">'dt'</span>] <span class="op">&gt;</span> timedelta(seconds<span class="op">=</span><span class="dv">1</span>)])</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the total duration, defined as the time between starting and ending the activity</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>total_duration <span class="op">=</span> gdf[<span class="st">'dt'</span>].<span class="bu">sum</span>()</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the active duration, defined as the total time minus any pauses</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>active_duration <span class="op">=</span> gdf.loc[gdf[<span class="st">'dt'</span>] <span class="op">==</span> timedelta(seconds<span class="op">=</span><span class="dv">1</span>), <span class="st">'dt'</span>].<span class="bu">sum</span>()</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate total distance, excluding pauses</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>total_distance_miles <span class="op">=</span> gdf.loc[(gdf[<span class="st">'dt'</span>] <span class="op">==</span> timedelta(seconds<span class="op">=</span><span class="dv">1</span>)), <span class="st">'dx'</span>].<span class="bu">sum</span>() <span class="op">/</span> <span class="dv">1609</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate average pace, exclude any pace over 10 min/mi since those are not representative of actual running</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>average_pace <span class="op">=</span> gdf.loc[gdf[<span class="st">"pace (min/mi)"</span>] <span class="op">&lt;</span> <span class="dv">10</span>, <span class="st">"pace (min/mi)"</span>].mean()</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate total ascent, excluding pauses</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>total_ascent <span class="op">=</span> gdf.loc[(gdf[<span class="st">'dt'</span>] <span class="op">==</span> timedelta(seconds<span class="op">=</span><span class="dv">1</span>)), <span class="st">'elevation'</span>].diff().loc[gdf[<span class="st">'elevation'</span>].diff() <span class="op">&gt;</span> <span class="dv">0</span>].<span class="bu">sum</span>()</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate total descent, excluding pauses</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>total_descent <span class="op">=</span> gdf.loc[(gdf[<span class="st">'dt'</span>] <span class="op">==</span> timedelta(seconds<span class="op">=</span><span class="dv">1</span>)), <span class="st">'elevation'</span>].diff().loc[gdf[<span class="st">'elevation'</span>].diff() <span class="op">&lt;</span> <span class="dv">0</span>].<span class="bu">sum</span>()</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="co"># split each pause segment into a LineString within a MultiLineString</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>fixed_track_line <span class="op">=</span> shapely.MultiLineString([shapely.LineString(group[<span class="st">'geometry'</span>]) <span class="cf">for</span> _, group <span class="kw">in</span> gdf.groupby(<span class="st">'pause_segment'</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="65f09f3f" class="cell" data-execution_count="26">
<div class="cell-output cell-output-stdout">
<pre><code>Number of Pauses: 3
Total Duration: 0 days 00:33:33
Active Duration: 0 days 00:33:17
Total Distance (miles): 4.084091745774948
Average Pace (min/mi): 8.14015279647961
Total Ascent (m): 27.357408000000078
Total Descent (m): -30.719911000000053

Fixed Track Line:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="showcase_files/figure-html/cell-27-output-2.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Now I will apply these GPX data extraction steps to each GPX file, and add the resulting summary statistics and fixed track line to our master dataframe.</p>
<div id="28231ec8" class="cell" data-execution_count="27">
<div class="cell-output cell-output-stdout">
<pre><code>Updated Master Dataframe:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">track_file</th>
<th data-quarto-table-cell-role="th">track_file_datetime</th>
<th data-quarto-table-cell-role="th">track_file_date</th>
<th data-quarto-table-cell-role="th">day_of_week</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">season</th>
<th data-quarto-table-cell-role="th">start_point</th>
<th data-quarto-table-cell-role="th">end_point</th>
<th data-quarto-table-cell-role="th">num_pauses</th>
<th data-quarto-table-cell-role="th">track_line</th>
<th data-quarto-table-cell-role="th">start_datetime</th>
<th data-quarto-table-cell-role="th">end_datetime</th>
<th data-quarto-table-cell-role="th">total_duration</th>
<th data-quarto-table-cell-role="th">active_duration</th>
<th data-quarto-table-cell-role="th">total_distance (mi)</th>
<th data-quarto-table-cell-role="th">average_pace (min/mi)</th>
<th data-quarto-table-cell-role="th">total_ascent (m)</th>
<th data-quarto-table-cell-role="th">total_descent (m)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">275</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2020-06-05 07:04:00-05:00</td>
<td>2020-06-05</td>
<td>Friday</td>
<td>Sophomore</td>
<td>Summer Training</td>
<td>POINT (-88.28675 41.9043)</td>
<td>POINT (-88.2866 41.9034)</td>
<td>3</td>
<td>MULTILINESTRING ((-88.28675 41.9043, -88.28674...</td>
<td>2020-06-05 11:38:16+00:00</td>
<td>2020-06-05 12:04:38+00:00</td>
<td>0 days 00:26:24</td>
<td>0 days 00:26:18</td>
<td>2.927488</td>
<td>8.831645</td>
<td>52.348479</td>
<td>-33.670257</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">291</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2020-06-23 07:00:00-05:00</td>
<td>2020-06-23</td>
<td>Tuesday</td>
<td>Sophomore</td>
<td>Summer Training</td>
<td>POINT (-88.31158 41.90829)</td>
<td>POINT (-88.31037 41.90433)</td>
<td>4</td>
<td>MULTILINESTRING ((-88.31158 41.90829, -88.3116...</td>
<td>2020-06-23 11:47:31+00:00</td>
<td>2020-06-23 12:00:03+00:00</td>
<td>0 days 00:11:45</td>
<td>0 days 00:07:24</td>
<td>0.882743</td>
<td>8.111984</td>
<td>26.179962</td>
<td>-11.133926</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">359</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2020-09-23 17:03:00-05:00</td>
<td>2020-09-23</td>
<td>Wednesday</td>
<td>Sophomore</td>
<td>XC Season</td>
<td>POINT (-88.27831 41.92712)</td>
<td>POINT (-88.279 41.92729)</td>
<td>2</td>
<td>MULTILINESTRING ((-88.27831 41.92712, -88.2783...</td>
<td>2020-09-23 21:42:58+00:00</td>
<td>2020-09-23 22:03:48+00:00</td>
<td>0 days 00:20:50</td>
<td>0 days 00:20:46</td>
<td>2.983654</td>
<td>7.004516</td>
<td>27.662580</td>
<td>-27.240553</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">383</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2020-10-10 07:47:00-05:00</td>
<td>2020-10-10</td>
<td>Saturday</td>
<td>Sophomore</td>
<td>XC Season</td>
<td>POINT (-88.27664 41.92875)</td>
<td>POINT (-88.27734 41.92827)</td>
<td>1</td>
<td>MULTILINESTRING ((-88.27664 41.92875, -88.2766...</td>
<td>2020-10-10 12:41:36+00:00</td>
<td>2020-10-10 12:47:05+00:00</td>
<td>0 days 00:05:32</td>
<td>0 days 00:05:29</td>
<td>0.945679</td>
<td>5.811499</td>
<td>5.083955</td>
<td>-3.399735</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">511</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2021-03-25 16:00:00-05:00</td>
<td>2021-03-25</td>
<td>Thursday</td>
<td>Sophomore</td>
<td>Winter Training</td>
<td>POINT (-88.27988 41.92862)</td>
<td>POINT (-88.27978 41.92844)</td>
<td>11</td>
<td>MULTILINESTRING ((-88.27988 41.92862, -88.2798...</td>
<td>2021-03-25 19:55:31+00:00</td>
<td>2021-03-25 21:00:54+00:00</td>
<td>0 days 00:50:47</td>
<td>0 days 00:48:38</td>
<td>6.597568</td>
<td>7.449268</td>
<td>111.392730</td>
<td>-111.677627</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">537</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2021-04-20 15:37:00-05:00</td>
<td>2021-04-20</td>
<td>Tuesday</td>
<td>Sophomore</td>
<td>Track Season</td>
<td>POINT (-88.27967 41.92859)</td>
<td>POINT (-88.27989 41.92845)</td>
<td>3</td>
<td>MULTILINESTRING ((-88.27967 41.92859, -88.2796...</td>
<td>2021-04-20 20:04:57+00:00</td>
<td>2021-04-20 20:37:47+00:00</td>
<td>0 days 00:31:49</td>
<td>0 days 00:31:10</td>
<td>4.083687</td>
<td>7.598700</td>
<td>29.133894</td>
<td>-28.981886</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">588</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2021-05-26 18:17:00-05:00</td>
<td>2021-05-26</td>
<td>Wednesday</td>
<td>Sophomore</td>
<td>Track Season</td>
<td>POINT (-88.27749 41.92852)</td>
<td>POINT (-88.27979 41.9285)</td>
<td>2</td>
<td>MULTILINESTRING ((-88.27749 41.92852, -88.2774...</td>
<td>2021-05-26 23:11:12+00:00</td>
<td>2021-05-26 23:17:13+00:00</td>
<td>0 days 00:06:03</td>
<td>0 days 00:05:56</td>
<td>0.659248</td>
<td>8.483895</td>
<td>3.812791</td>
<td>-5.706117</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">708</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2021-09-20 15:59:00-05:00</td>
<td>2021-09-20</td>
<td>Monday</td>
<td>Junior</td>
<td>XC Season</td>
<td>POINT (-88.27976 41.92868)</td>
<td>POINT (-88.27977 41.92846)</td>
<td>19</td>
<td>MULTILINESTRING ((-88.27976 41.92868, -88.2797...</td>
<td>2021-09-20 20:03:09+00:00</td>
<td>2021-09-20 20:59:16+00:00</td>
<td>0 days 00:53:10</td>
<td>0 days 00:48:52</td>
<td>6.430037</td>
<td>7.599476</td>
<td>60.793227</td>
<td>-61.113219</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">907</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2022-12-12 15:47:00-06:00</td>
<td>2022-12-12</td>
<td>Monday</td>
<td>Senior</td>
<td>Winter Training</td>
<td>POINT (-88.27981 41.92881)</td>
<td>POINT (-88.2799 41.92846)</td>
<td>8</td>
<td>MULTILINESTRING ((-88.27981 41.92881, -88.2798...</td>
<td>2022-12-12 20:51:21+00:00</td>
<td>2022-12-12 21:47:41+00:00</td>
<td>0 days 00:53:59</td>
<td>0 days 00:50:32</td>
<td>6.184217</td>
<td>8.125310</td>
<td>60.195813</td>
<td>-60.283697</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">930</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2023-01-17 16:14:00-06:00</td>
<td>2023-01-17</td>
<td>Tuesday</td>
<td>Senior</td>
<td>Winter Training</td>
<td>POINT (-88.27986 41.9285)</td>
<td>POINT (-88.27969 41.92841)</td>
<td>9</td>
<td>MULTILINESTRING ((-88.27986 41.9285, -88.27986...</td>
<td>2023-01-17 20:58:17+00:00</td>
<td>2023-01-17 22:14:30+00:00</td>
<td>0 days 01:11:52</td>
<td>0 days 00:55:18</td>
<td>7.395419</td>
<td>7.511521</td>
<td>46.386440</td>
<td>-46.506581</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataframe Length: 1023 Rows</code></pre>
</div>
</div>
</section>
<section id="activity-recombination" class="level4">
<h4 class="anchored" data-anchor-id="activity-recombination">2.4.4 Activity Recombination</h4>
<p>Sometimes, I chose to record a workout all in the same recorded activity, and other times I broke it into several recorded activities. To be able to effectively cluster routes, I need to standardize this. I am going to flatten all activities recorded on the same day into one workout entry with one combined GPX track. This will also fix any cases where I accidently ended an activity mid-run and had to start another. However, I will have to take special care to separate out doubles. During the season, we would run twice on some days, in the morning and the afternoon.</p>
<p>First, I will identify all dates with more than one recorded activity.</p>
<div id="3cf23aba" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># isolate dates with multiple runs for further processing</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>counts <span class="op">=</span> gdf_track_info[[<span class="st">"track_file_date"</span>, <span class="st">"start_datetime"</span>]].groupby(<span class="st">"track_file_date"</span>).agg(<span class="st">"count"</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>multple_dates <span class="op">=</span> counts.loc[counts[<span class="st">"start_datetime"</span>] <span class="op">&gt;</span> <span class="dv">1</span>].index</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># dataframe with single-run dates</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>gdf_track_info_singles <span class="op">=</span> gdf_track_info.loc[<span class="op">~</span>gdf_track_info[<span class="st">'track_file_date'</span>].isin(multple_dates)]</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="co"># dataframe with multiple-run dates</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>gdf_track_info_multiples <span class="op">=</span> gdf_track_info.loc[gdf_track_info[<span class="st">'track_file_date'</span>].isin(multple_dates)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, I need to find a way to identify doubles. Let’s look at the distribution of the time between activities for all of the days with more than one recorded activity. To do this I will group all the workouts by their date and calculate the time between same-day workouts.</p>
<div id="d904b274" class="cell" data-execution_count="29">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="showcase_files/figure-html/cell-30-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>There is a excellently clear bimodal distribution. The mode around zero corresponds to the workout activities that should be aggregated together, and the mode around nine hours corresponds to doubles. I have marked three hours as an appropriate threshold. For the two activities just under 4 hours, I manually checked and they are doubles. Now, I will go through each date group, if there is a double, I will keep it separate, and then aggregate the other activities into one.</p>
<div id="1778e2cf" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> agg_track_lines(series):</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    lines <span class="op">=</span> []</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> mline <span class="kw">in</span> series:</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> line <span class="kw">in</span> mline.geoms:</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>            lines.append(line)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> shapely.MultiLineString(lines)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>agg_dict <span class="op">=</span> {</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"track_file"</span>: <span class="st">'sum'</span>,</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"track_file_datetime"</span>: <span class="st">'min'</span>,</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"day_of_week"</span>: <span class="st">'first'</span>,</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"start_datetime"</span>: <span class="st">'first'</span>,</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"end_datetime"</span>: <span class="st">'last'</span>,</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"year"</span>: <span class="st">'first'</span>,</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"season"</span>: <span class="st">'first'</span>,</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"num_pauses"</span>: <span class="st">'sum'</span>,</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"total_duration"</span>: <span class="st">'sum'</span>,</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"active_duration"</span>: <span class="st">'sum'</span>,</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"total_distance (mi)"</span>: <span class="st">'sum'</span>,</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"average_pace (min/mi)"</span>: <span class="st">'mean'</span>,</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"total_ascent (m)"</span>: <span class="st">'sum'</span>,</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"total_descent (m)"</span>: <span class="st">'sum'</span>,</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"start_point"</span>: <span class="st">'first'</span>,</span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"end_point"</span>: <span class="st">'last'</span>,</span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"track_line"</span>: agg_track_lines</span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> group_name, group <span class="kw">in</span> gdf_track_info_multiples.groupby(<span class="st">"track_file_date"</span>):</span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a>    split <span class="op">=</span> group[<span class="st">'start_datetime'</span>].diff().<span class="bu">apply</span>(<span class="kw">lambda</span> x: x.total_seconds()<span class="op">/</span><span class="dv">3600</span>) <span class="op">&gt;</span> <span class="dv">3</span></span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> split.<span class="bu">sum</span>() <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a>        <span class="co"># add condensed first session</span></span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a>        temp <span class="op">=</span> group[:split.argmax()].groupby(<span class="st">"track_file_date"</span>).agg(agg_dict).reset_index()</span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a>        temp[<span class="st">"num_pauses"</span>] <span class="op">=</span> temp[<span class="st">"num_pauses"</span>] <span class="op">+</span> <span class="bu">len</span>(group[:split.argmax()]) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a>        rows.append(temp)</span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a>        <span class="co"># add condensed second session</span></span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a>        temp <span class="op">=</span> group[split.argmax():].groupby(<span class="st">"track_file_date"</span>).agg(agg_dict).reset_index()</span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a>        temp[<span class="st">"num_pauses"</span>] <span class="op">=</span> temp[<span class="st">"num_pauses"</span>] <span class="op">+</span> <span class="bu">len</span>(group[split.argmax():]) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb34-40"><a href="#cb34-40" aria-hidden="true" tabindex="-1"></a>        rows.append(temp)</span>
<span id="cb34-41"><a href="#cb34-41" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb34-42"><a href="#cb34-42" aria-hidden="true" tabindex="-1"></a>        <span class="co"># add condensed session</span></span>
<span id="cb34-43"><a href="#cb34-43" aria-hidden="true" tabindex="-1"></a>        rows.append(group.groupby(<span class="st">"track_file_date"</span>).agg(agg_dict).reset_index())</span>
<span id="cb34-44"><a href="#cb34-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-45"><a href="#cb34-45" aria-hidden="true" tabindex="-1"></a>gdf_track_info_multiples_combined <span class="op">=</span> gpd.GeoDataFrame(pd.concat(rows), geometry<span class="op">=</span><span class="st">"track_line"</span>, crs<span class="op">=</span><span class="st">"EPSG:4326"</span>)</span>
<span id="cb34-46"><a href="#cb34-46" aria-hidden="true" tabindex="-1"></a>gdf_track_info_multiples_combined[<span class="st">"start_point"</span>] <span class="op">=</span> gpd.GeoSeries(gdf_track_info_multiples_combined[<span class="st">"end_point"</span>], crs<span class="op">=</span>gdf_track_info_multiples_combined.crs)</span>
<span id="cb34-47"><a href="#cb34-47" aria-hidden="true" tabindex="-1"></a>gdf_track_info_multiples_combined[<span class="st">"end_point"</span>] <span class="op">=</span> gpd.GeoSeries(gdf_track_info_multiples_combined[<span class="st">"end_point"</span>], crs<span class="op">=</span>gdf_track_info_multiples_combined.crs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="ccda185c" class="cell" data-execution_count="31">
<div class="cell-output cell-output-stdout">
<pre><code>Table with multiples combined</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">track_file_date</th>
<th data-quarto-table-cell-role="th">track_file</th>
<th data-quarto-table-cell-role="th">track_file_datetime</th>
<th data-quarto-table-cell-role="th">day_of_week</th>
<th data-quarto-table-cell-role="th">start_datetime</th>
<th data-quarto-table-cell-role="th">end_datetime</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">season</th>
<th data-quarto-table-cell-role="th">num_pauses</th>
<th data-quarto-table-cell-role="th">total_duration</th>
<th data-quarto-table-cell-role="th">active_duration</th>
<th data-quarto-table-cell-role="th">total_distance (mi)</th>
<th data-quarto-table-cell-role="th">average_pace (min/mi)</th>
<th data-quarto-table-cell-role="th">total_ascent (m)</th>
<th data-quarto-table-cell-role="th">total_descent (m)</th>
<th data-quarto-table-cell-role="th">start_point</th>
<th data-quarto-table-cell-role="th">end_point</th>
<th data-quarto-table-cell-role="th">track_line</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2019-06-20</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-06-20 07:21:00-05:00</td>
<td>Thursday</td>
<td>2019-06-20 11:41:38+00:00</td>
<td>2019-06-20 12:21:03+00:00</td>
<td>Freshman</td>
<td>Summer Training</td>
<td>4</td>
<td>0 days 00:39:25</td>
<td>0 days 00:39:17</td>
<td>3.103609</td>
<td>9.793146</td>
<td>29.641343</td>
<td>-27.690675</td>
<td>POINT (-88.31042 41.90834)</td>
<td>POINT (-88.31042 41.90834)</td>
<td>MULTILINESTRING ((-88.30986 41.9092, -88.30985...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>2019-06-20</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-06-20 19:20:00-05:00</td>
<td>Thursday</td>
<td>2019-06-21 00:00:35+00:00</td>
<td>2019-06-21 00:32:57+00:00</td>
<td>Freshman</td>
<td>Summer Training</td>
<td>2</td>
<td>0 days 00:28:38</td>
<td>0 days 00:28:36</td>
<td>2.814023</td>
<td>9.281108</td>
<td>35.128156</td>
<td>-42.620542</td>
<td>POINT (-88.28806 41.90672)</td>
<td>POINT (-88.28806 41.90672)</td>
<td>MULTILINESTRING ((-88.28697 41.9046, -88.28698...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2019-06-26</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-06-26 07:11:00-05:00</td>
<td>Wednesday</td>
<td>2019-06-26 11:52:24+00:00</td>
<td>2019-06-26 13:01:36+00:00</td>
<td>Freshman</td>
<td>Summer Training</td>
<td>7</td>
<td>0 days 01:05:52</td>
<td>0 days 00:55:46</td>
<td>4.353060</td>
<td>9.419139</td>
<td>135.423601</td>
<td>-90.714006</td>
<td>POINT (-88.32042 41.90189)</td>
<td>POINT (-88.32042 41.90189)</td>
<td>MULTILINESTRING ((-88.3199 41.90209, -88.3199 ...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>2019-07-17</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-07-17 06:59:00-05:00</td>
<td>Wednesday</td>
<td>2019-07-17 11:53:18+00:00</td>
<td>2019-07-17 12:34:28+00:00</td>
<td>Freshman</td>
<td>Summer Training</td>
<td>0</td>
<td>0 days 00:18:22</td>
<td>0 days 00:18:22</td>
<td>1.942416</td>
<td>8.910520</td>
<td>60.246660</td>
<td>-42.594987</td>
<td>POINT (-88.32055 41.90178)</td>
<td>POINT (-88.32055 41.90178)</td>
<td>MULTILINESTRING ((-88.31905 41.90737, -88.3190...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2019-07-25</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-07-25 06:52:00-05:00</td>
<td>Thursday</td>
<td>2019-07-25 11:44:12+00:00</td>
<td>2019-07-25 13:04:28+00:00</td>
<td>Freshman</td>
<td>Summer Training</td>
<td>1</td>
<td>0 days 00:16:34</td>
<td>0 days 00:15:46</td>
<td>1.761788</td>
<td>8.649105</td>
<td>15.534822</td>
<td>-13.028947</td>
<td>POINT (-88.27989 41.92837)</td>
<td>POINT (-88.27989 41.92837)</td>
<td>MULTILINESTRING ((-88.27982 41.92933, -88.2798...</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataframe Length: 184 Rows</code></pre>
</div>
</div>
<div id="b646eedf" class="cell" data-execution_count="32">
<div class="cell-output cell-output-stdout">
<pre><code>Current Master Dataframe:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">track_file</th>
<th data-quarto-table-cell-role="th">track_file_datetime</th>
<th data-quarto-table-cell-role="th">track_file_date</th>
<th data-quarto-table-cell-role="th">day_of_week</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">season</th>
<th data-quarto-table-cell-role="th">start_point</th>
<th data-quarto-table-cell-role="th">end_point</th>
<th data-quarto-table-cell-role="th">num_pauses</th>
<th data-quarto-table-cell-role="th">track_line</th>
<th data-quarto-table-cell-role="th">start_datetime</th>
<th data-quarto-table-cell-role="th">end_datetime</th>
<th data-quarto-table-cell-role="th">total_duration</th>
<th data-quarto-table-cell-role="th">active_duration</th>
<th data-quarto-table-cell-role="th">total_distance (mi)</th>
<th data-quarto-table-cell-role="th">average_pace (min/mi)</th>
<th data-quarto-table-cell-role="th">total_ascent (m)</th>
<th data-quarto-table-cell-role="th">total_descent (m)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-06-10 07:46:00-05:00</td>
<td>2019-06-10</td>
<td>Monday</td>
<td>Freshman</td>
<td>Summer Training</td>
<td>POINT (-88.32154 41.91101)</td>
<td>POINT (-88.32166 41.9109)</td>
<td>0</td>
<td>MULTILINESTRING ((-88.32154 41.91101, -88.3215...</td>
<td>2019-06-10 11:57:42+00:00</td>
<td>2019-06-10 12:46:10+00:00</td>
<td>0 days 00:48:28</td>
<td>0 days 00:48:28</td>
<td>3.060933</td>
<td>8.542777</td>
<td>39.011887</td>
<td>-38.079392</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-06-11 07:32:00-05:00</td>
<td>2019-06-11</td>
<td>Tuesday</td>
<td>Freshman</td>
<td>Summer Training</td>
<td>POINT (-88.34764 41.928)</td>
<td>POINT (-88.34792 41.92783)</td>
<td>5</td>
<td>MULTILINESTRING ((-88.34764 41.928, -88.34764 ...</td>
<td>2019-06-11 11:59:03+00:00</td>
<td>2019-06-11 12:32:23+00:00</td>
<td>0 days 00:33:20</td>
<td>0 days 00:33:10</td>
<td>3.154848</td>
<td>8.785222</td>
<td>60.890730</td>
<td>-61.285231</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-06-12 07:35:00-05:00</td>
<td>2019-06-12</td>
<td>Wednesday</td>
<td>Freshman</td>
<td>Summer Training</td>
<td>POINT (-88.32153 41.91251)</td>
<td>POINT (-88.32172 41.911)</td>
<td>5</td>
<td>MULTILINESTRING ((-88.32153 41.91251, -88.3215...</td>
<td>2019-06-12 11:53:36+00:00</td>
<td>2019-06-12 12:35:13+00:00</td>
<td>0 days 00:41:43</td>
<td>0 days 00:30:46</td>
<td>2.521019</td>
<td>8.567542</td>
<td>68.381334</td>
<td>-63.546495</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-06-17 07:22:00-05:00</td>
<td>2019-06-17</td>
<td>Monday</td>
<td>Freshman</td>
<td>Summer Training</td>
<td>POINT (-88.32145 41.911)</td>
<td>POINT (-88.32154 41.91096)</td>
<td>0</td>
<td>MULTILINESTRING ((-88.32145 41.911, -88.32143 ...</td>
<td>2019-06-17 11:52:32+00:00</td>
<td>2019-06-17 12:22:32+00:00</td>
<td>0 days 00:30:00</td>
<td>0 days 00:30:00</td>
<td>2.981428</td>
<td>9.099587</td>
<td>43.081880</td>
<td>-42.863923</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>/Users/ryansponzilli/Developer/Python Projects...</td>
<td>2019-06-18 07:19:00-05:00</td>
<td>2019-06-18</td>
<td>Tuesday</td>
<td>Freshman</td>
<td>Summer Training</td>
<td>POINT (-88.35416 41.92575)</td>
<td>POINT (-88.34797 41.92783)</td>
<td>3</td>
<td>MULTILINESTRING ((-88.35416 41.92575, -88.3541...</td>
<td>2019-06-18 11:53:58+00:00</td>
<td>2019-06-18 12:19:21+00:00</td>
<td>0 days 00:25:23</td>
<td>0 days 00:25:03</td>
<td>2.343798</td>
<td>9.394596</td>
<td>49.200207</td>
<td>-46.531003</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataframe Length: 803 Rows</code></pre>
</div>
</div>
</section>
<section id="region-assignment" class="level4">
<h4 class="anchored" data-anchor-id="region-assignment">2.4.5 Region Assignment</h4>
<div id="4e327c68" class="cell" data-execution_count="33">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="showcase_files/figure-html/cell-34-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="route-clustering" class="level2">
<h2 class="anchored" data-anchor-id="route-clustering">4. Route Clustering</h2>
<p>Route Classification</p>
</section>
<section id="route-decomposition" class="level2">
<h2 class="anchored" data-anchor-id="route-decomposition">5. Route Decomposition</h2>
</section>
<section id="run-type-classification" class="level2">
<h2 class="anchored" data-anchor-id="run-type-classification">5. Run Type Classification</h2>
<p>Run Type Classification</p>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">6. Analysis</h2>
<p>Analysis</p>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">7. Summary</h2>
<p>Summary</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>